/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusType = IDL.Variant({
  'NonAC_Seater' : IDL.Null,
  'AC_Sleeper' : IDL.Null,
  'NonAC_Sleeper' : IDL.Null,
  'AC_Seater' : IDL.Null,
});
export const AddBusInput = IDL.Record({
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'droppingPoints' : IDL.Vec(IDL.Text),
  'busType' : BusType,
  'boardingPoints' : IDL.Vec(IDL.Text),
  'arrivalTime' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'operatorName' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'totalSeats' : IDL.Nat,
  'price' : IDL.Nat,
});
export const BusId = IDL.Nat;
export const Timestamp = IDL.Int;
export const BusView = IDL.Record({
  'id' : BusId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'droppingPoints' : IDL.Vec(IDL.Text),
  'busType' : BusType,
  'boardingPoints' : IDL.Vec(IDL.Text),
  'arrivalTime' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'operatorName' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'totalSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
});
export const DiscountType = IDL.Variant({
  'Percent' : IDL.Null,
  'Fixed' : IDL.Null,
});
export const CouponApplicableFor = IDL.Variant({
  'All' : IDL.Null,
  'Bus' : IDL.Null,
  'Flight' : IDL.Null,
  'Train' : IDL.Null,
  'Hotel' : IDL.Null,
});
export const AddCouponInput = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : Timestamp,
  'maxDiscount' : IDL.Nat,
  'minBookingAmount' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'usageLimit' : IDL.Nat,
  'applicableFor' : CouponApplicableFor,
});
export const CouponId = IDL.Nat;
export const CouponView = IDL.Record({
  'id' : CouponId,
  'discountValue' : IDL.Nat,
  'expiresAt' : Timestamp,
  'maxDiscount' : IDL.Nat,
  'minBookingAmount' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Nat,
  'applicableFor' : CouponApplicableFor,
});
export const CabinClass = IDL.Variant({
  'Business' : IDL.Null,
  'First' : IDL.Null,
  'Economy' : IDL.Null,
});
export const AddFlightInput = IDL.Record({
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'flightNumber' : IDL.Text,
  'departureTime' : IDL.Text,
  'cabin' : CabinClass,
  'from' : IDL.Text,
  'baggage' : IDL.Text,
  'stops' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'airline' : IDL.Text,
  'price' : IDL.Nat,
});
export const FlightId = IDL.Nat;
export const FlightView = IDL.Record({
  'id' : FlightId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'flightNumber' : IDL.Text,
  'departureTime' : IDL.Text,
  'cabin' : CabinClass,
  'from' : IDL.Text,
  'baggage' : IDL.Text,
  'createdAt' : Timestamp,
  'stops' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'airline' : IDL.Text,
  'price' : IDL.Nat,
});
export const AddHotelInput = IDL.Record({
  'starRating' : IDL.Nat,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'checkInTime' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'totalRooms' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const HotelId = IDL.Nat;
export const HotelView = IDL.Record({
  'id' : HotelId,
  'availableRooms' : IDL.Nat,
  'starRating' : IDL.Nat,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'checkInTime' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'checkOutTime' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'totalRooms' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const AddMealCampaignInput = IDL.Record({
  'endDate' : Timestamp,
  'eligibleForFirstTime' : IDL.Bool,
  'name' : IDL.Text,
  'eligibleForVIP' : IDL.Bool,
  'minDistanceKm' : IDL.Nat,
  'startDate' : Timestamp,
  'mealTypes' : IDL.Vec(IDL.Text),
});
export const MealCampaignId = IDL.Nat;
export const MealCampaignView = IDL.Record({
  'id' : MealCampaignId,
  'endDate' : Timestamp,
  'eligibleForFirstTime' : IDL.Bool,
  'name' : IDL.Text,
  'eligibleForVIP' : IDL.Bool,
  'isActive' : IDL.Bool,
  'minDistanceKm' : IDL.Nat,
  'startDate' : Timestamp,
  'mealTypes' : IDL.Vec(IDL.Text),
});
export const AddReviewInput = IDL.Record({
  'referenceId' : IDL.Nat,
  'comment' : IDL.Text,
  'bookingType' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const ReviewView = IDL.Record({
  'id' : ReviewId,
  'userName' : IDL.Text,
  'isApproved' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Nat,
  'comment' : IDL.Text,
  'bookingType' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TrainClass = IDL.Record({
  'fare' : IDL.Nat,
  'available' : IDL.Nat,
  'className' : IDL.Text,
});
export const RouteStop = IDL.Record({
  'arrivalTime' : IDL.Text,
  'station' : IDL.Text,
  'departureTime' : IDL.Text,
  'dayNumber' : IDL.Nat,
});
export const AddTrainInput = IDL.Record({
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'trainNumber' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'classes' : IDL.Vec(TrainClass),
  'route' : IDL.Vec(RouteStop),
});
export const TrainId = IDL.Nat;
export const TrainView = IDL.Record({
  'id' : TrainId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'trainNumber' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'classes' : IDL.Vec(TrainClass),
  'route' : IDL.Vec(RouteStop),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const BookingType = IDL.Variant({
  'Bus' : IDL.Null,
  'Flight' : IDL.Null,
  'Train' : IDL.Null,
  'Hotel' : IDL.Null,
});
export const MealEligibilityResult = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'eligible' : IDL.Bool,
  'campaignName' : IDL.Opt(IDL.Text),
  'mealTypes' : IDL.Vec(IDL.Text),
});
export const PassengerDetail = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'seatNumber' : IDL.Text,
});
export const CreateBookingInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'passengerDetails' : IDL.Vec(PassengerDetail),
  'toLocation' : IDL.Text,
  'referenceId' : IDL.Nat,
  'fromLocation' : IDL.Text,
  'distanceKm' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'bookingType' : BookingType,
  'travelDate' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Refunded' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const MealType = IDL.Variant({
  'Veg' : IDL.Null,
  'NonVeg' : IDL.Null,
  'Beverages' : IDL.Null,
  'Snacks' : IDL.Null,
});
export const SpecialFeatures = IDL.Record({
  'freeFoodCouponCode' : IDL.Opt(IDL.Text),
  'freeFoodIncluded' : IDL.Bool,
  'mealType' : IDL.Opt(MealType),
});
export const BookingView = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'passengerDetails' : IDL.Vec(PassengerDetail),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'toLocation' : IDL.Text,
  'referenceId' : IDL.Nat,
  'fromLocation' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'bookingType' : BookingType,
  'travelDate' : IDL.Text,
  'specialFeatures' : SpecialFeatures,
});
export const UpdateUserInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'VIP' : IDL.Null,
  'User' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserView = IDL.Record({
  'id' : UserId,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'totalBookings' : IDL.Nat,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'isFirstTimeUser' : IDL.Bool,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingBookings' : IDL.Nat,
  'activeBuses' : IDL.Nat,
  'activeHotels' : IDL.Nat,
  'activeFlights' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'activeTrains' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCoupons' : IDL.Nat,
  'activeMealCampaigns' : IDL.Nat,
});
export const LoyaltyTxId = IDL.Nat;
export const LoyaltyTransactionType = IDL.Variant({
  'Earn' : IDL.Null,
  'Redeem' : IDL.Null,
});
export const LoyaltyTransaction = IDL.Record({
  'id' : LoyaltyTxId,
  'bookingId' : IDL.Opt(BookingId),
  'transactionType' : LoyaltyTransactionType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'points' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const PaymentTransactionStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Success' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'NetBanking' : IDL.Null,
  'Wallet' : IDL.Null,
});
export const PaymentView = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentTransactionStatus,
  'method' : PaymentMethod,
  'bookingId' : BookingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const RevenuePeriod = IDL.Variant({
  'Day' : IDL.Null,
  'Week' : IDL.Null,
  'Year' : IDL.Null,
  'Month' : IDL.Null,
});
export const RevenueStats = IDL.Record({
  'period' : RevenuePeriod,
  'bookingsByType' : IDL.Vec(
    IDL.Record({
      'revenue' : IDL.Nat,
      'count' : IDL.Nat,
      'bookingType' : IDL.Text,
    })
  ),
  'totalRevenue' : IDL.Nat,
});
export const RoomId = IDL.Nat;
export const RoomType = IDL.Variant({
  'Suite' : IDL.Null,
  'Double' : IDL.Null,
  'Deluxe' : IDL.Null,
  'Single' : IDL.Null,
});
export const RoomView = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'hotelId' : HotelId,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'available' : IDL.Bool,
  'capacity' : IDL.Nat,
  'price' : IDL.Nat,
  'roomType' : RoomType,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'System' : IDL.Null,
  'Booking' : IDL.Null,
  'Offer' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const ProcessPaymentInput = IDL.Record({
  'method' : PaymentMethod,
  'bookingId' : BookingId,
  'amount' : IDL.Nat,
});
export const UpdateBusInput = IDL.Record({
  'id' : BusId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'droppingPoints' : IDL.Vec(IDL.Text),
  'busType' : BusType,
  'boardingPoints' : IDL.Vec(IDL.Text),
  'arrivalTime' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'operatorName' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'totalSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
});
export const UpdateCouponInput = IDL.Record({
  'id' : CouponId,
  'discountValue' : IDL.Nat,
  'expiresAt' : Timestamp,
  'maxDiscount' : IDL.Nat,
  'minBookingAmount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Nat,
  'applicableFor' : CouponApplicableFor,
});
export const UpdateFlightInput = IDL.Record({
  'id' : FlightId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'flightNumber' : IDL.Text,
  'departureTime' : IDL.Text,
  'cabin' : CabinClass,
  'from' : IDL.Text,
  'baggage' : IDL.Text,
  'stops' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'airline' : IDL.Text,
  'price' : IDL.Nat,
});
export const UpdateHotelInput = IDL.Record({
  'id' : HotelId,
  'availableRooms' : IDL.Nat,
  'starRating' : IDL.Nat,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'checkInTime' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'checkOutTime' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'totalRooms' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UpdateMealCampaignInput = IDL.Record({
  'id' : MealCampaignId,
  'endDate' : Timestamp,
  'eligibleForFirstTime' : IDL.Bool,
  'name' : IDL.Text,
  'eligibleForVIP' : IDL.Bool,
  'isActive' : IDL.Bool,
  'minDistanceKm' : IDL.Nat,
  'startDate' : Timestamp,
  'mealTypes' : IDL.Vec(IDL.Text),
});
export const UpdateTrainInput = IDL.Record({
  'id' : TrainId,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'trainNumber' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'classes' : IDL.Vec(TrainClass),
  'route' : IDL.Vec(RouteStop),
});
export const ValidateCouponResult = IDL.Record({
  'valid' : IDL.Bool,
  'discountAmount' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBus' : IDL.Func([AddBusInput], [BusView], []),
  'addCoupon' : IDL.Func([AddCouponInput], [CouponView], []),
  'addFlight' : IDL.Func([AddFlightInput], [FlightView], []),
  'addHotel' : IDL.Func([AddHotelInput], [HotelView], []),
  'addMealCampaign' : IDL.Func([AddMealCampaignInput], [MealCampaignView], []),
  'addReview' : IDL.Func([AddReviewInput], [ReviewView], []),
  'addTrain' : IDL.Func([AddTrainInput], [TrainView], []),
  'approveReview' : IDL.Func([ReviewId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'callOpenAI' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'checkMealEligibility' : IDL.Func(
      [IDL.Nat, BookingType],
      [MealEligibilityResult],
      ['query'],
    ),
  'createBooking' : IDL.Func([CreateBookingInput], [BookingView], []),
  'createOrUpdateUser' : IDL.Func([UpdateUserInput], [UserView], []),
  'deleteBus' : IDL.Func([BusId], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
  'deleteFlight' : IDL.Func([FlightId], [IDL.Bool], []),
  'deleteHotel' : IDL.Func([HotelId], [IDL.Bool], []),
  'deleteTrain' : IDL.Func([TrainId], [IDL.Bool], []),
  'getActiveMealCampaigns' : IDL.Func(
      [],
      [IDL.Vec(MealCampaignView)],
      ['query'],
    ),
  'getAdminDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(ReviewView)], ['query']),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
  'getBus' : IDL.Func([BusId], [IDL.Opt(BusView)], ['query']),
  'getBuses' : IDL.Func([], [IDL.Vec(BusView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(CouponView)], ['query']),
  'getFlight' : IDL.Func([FlightId], [IDL.Opt(FlightView)], ['query']),
  'getFlights' : IDL.Func([], [IDL.Vec(FlightView)], ['query']),
  'getHotel' : IDL.Func([HotelId], [IDL.Opt(HotelView)], ['query']),
  'getHotels' : IDL.Func([], [IDL.Vec(HotelView)], ['query']),
  'getLoyaltyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getLoyaltyHistory' : IDL.Func([], [IDL.Vec(LoyaltyTransaction)], ['query']),
  'getMealCampaigns' : IDL.Func([], [IDL.Vec(MealCampaignView)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'getPaymentByBooking' : IDL.Func(
      [BookingId],
      [IDL.Opt(PaymentView)],
      ['query'],
    ),
  'getRevenueStats' : IDL.Func([RevenuePeriod], [RevenueStats], ['query']),
  'getReviews' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(ReviewView)],
      ['query'],
    ),
  'getRoomsByHotel' : IDL.Func([HotelId], [IDL.Vec(RoomView)], ['query']),
  'getTrain' : IDL.Func([TrainId], [IDL.Opt(TrainView)], ['query']),
  'getTrains' : IDL.Func([], [IDL.Vec(TrainView)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(PaymentView)], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'processPayment' : IDL.Func([ProcessPaymentInput], [PaymentView], []),
  'searchBuses' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(BusView)],
      ['query'],
    ),
  'searchFlights' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(FlightView)],
      ['query'],
    ),
  'searchHotels' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(HotelView)],
      ['query'],
    ),
  'searchTrains' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(TrainView)],
      ['query'],
    ),
  'sendNotificationToUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, NotificationType],
      [],
      [],
    ),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [IDL.Bool], []),
  'updateBus' : IDL.Func([UpdateBusInput], [IDL.Opt(BusView)], []),
  'updateCoupon' : IDL.Func([UpdateCouponInput], [IDL.Opt(CouponView)], []),
  'updateFlight' : IDL.Func([UpdateFlightInput], [IDL.Opt(FlightView)], []),
  'updateHotel' : IDL.Func([UpdateHotelInput], [IDL.Opt(HotelView)], []),
  'updateMealCampaign' : IDL.Func(
      [UpdateMealCampaignInput],
      [IDL.Opt(MealCampaignView)],
      [],
    ),
  'updateTrain' : IDL.Func([UpdateTrainInput], [IDL.Opt(TrainView)], []),
  'updateUserProfile' : IDL.Func([UpdateUserInput], [UserView], []),
  'validateCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat, BookingType],
      [ValidateCouponResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusType = IDL.Variant({
    'NonAC_Seater' : IDL.Null,
    'AC_Sleeper' : IDL.Null,
    'NonAC_Sleeper' : IDL.Null,
    'AC_Seater' : IDL.Null,
  });
  const AddBusInput = IDL.Record({
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'droppingPoints' : IDL.Vec(IDL.Text),
    'busType' : BusType,
    'boardingPoints' : IDL.Vec(IDL.Text),
    'arrivalTime' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'operatorName' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'totalSeats' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const BusId = IDL.Nat;
  const Timestamp = IDL.Int;
  const BusView = IDL.Record({
    'id' : BusId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'droppingPoints' : IDL.Vec(IDL.Text),
    'busType' : BusType,
    'boardingPoints' : IDL.Vec(IDL.Text),
    'arrivalTime' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'operatorName' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'totalSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
  });
  const DiscountType = IDL.Variant({
    'Percent' : IDL.Null,
    'Fixed' : IDL.Null,
  });
  const CouponApplicableFor = IDL.Variant({
    'All' : IDL.Null,
    'Bus' : IDL.Null,
    'Flight' : IDL.Null,
    'Train' : IDL.Null,
    'Hotel' : IDL.Null,
  });
  const AddCouponInput = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : Timestamp,
    'maxDiscount' : IDL.Nat,
    'minBookingAmount' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'usageLimit' : IDL.Nat,
    'applicableFor' : CouponApplicableFor,
  });
  const CouponId = IDL.Nat;
  const CouponView = IDL.Record({
    'id' : CouponId,
    'discountValue' : IDL.Nat,
    'expiresAt' : Timestamp,
    'maxDiscount' : IDL.Nat,
    'minBookingAmount' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Nat,
    'applicableFor' : CouponApplicableFor,
  });
  const CabinClass = IDL.Variant({
    'Business' : IDL.Null,
    'First' : IDL.Null,
    'Economy' : IDL.Null,
  });
  const AddFlightInput = IDL.Record({
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'flightNumber' : IDL.Text,
    'departureTime' : IDL.Text,
    'cabin' : CabinClass,
    'from' : IDL.Text,
    'baggage' : IDL.Text,
    'stops' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'airline' : IDL.Text,
    'price' : IDL.Nat,
  });
  const FlightId = IDL.Nat;
  const FlightView = IDL.Record({
    'id' : FlightId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'flightNumber' : IDL.Text,
    'departureTime' : IDL.Text,
    'cabin' : CabinClass,
    'from' : IDL.Text,
    'baggage' : IDL.Text,
    'createdAt' : Timestamp,
    'stops' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'airline' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AddHotelInput = IDL.Record({
    'starRating' : IDL.Nat,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'checkInTime' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'totalRooms' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const HotelId = IDL.Nat;
  const HotelView = IDL.Record({
    'id' : HotelId,
    'availableRooms' : IDL.Nat,
    'starRating' : IDL.Nat,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'checkInTime' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'checkOutTime' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'totalRooms' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const AddMealCampaignInput = IDL.Record({
    'endDate' : Timestamp,
    'eligibleForFirstTime' : IDL.Bool,
    'name' : IDL.Text,
    'eligibleForVIP' : IDL.Bool,
    'minDistanceKm' : IDL.Nat,
    'startDate' : Timestamp,
    'mealTypes' : IDL.Vec(IDL.Text),
  });
  const MealCampaignId = IDL.Nat;
  const MealCampaignView = IDL.Record({
    'id' : MealCampaignId,
    'endDate' : Timestamp,
    'eligibleForFirstTime' : IDL.Bool,
    'name' : IDL.Text,
    'eligibleForVIP' : IDL.Bool,
    'isActive' : IDL.Bool,
    'minDistanceKm' : IDL.Nat,
    'startDate' : Timestamp,
    'mealTypes' : IDL.Vec(IDL.Text),
  });
  const AddReviewInput = IDL.Record({
    'referenceId' : IDL.Nat,
    'comment' : IDL.Text,
    'bookingType' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const ReviewView = IDL.Record({
    'id' : ReviewId,
    'userName' : IDL.Text,
    'isApproved' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Nat,
    'comment' : IDL.Text,
    'bookingType' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TrainClass = IDL.Record({
    'fare' : IDL.Nat,
    'available' : IDL.Nat,
    'className' : IDL.Text,
  });
  const RouteStop = IDL.Record({
    'arrivalTime' : IDL.Text,
    'station' : IDL.Text,
    'departureTime' : IDL.Text,
    'dayNumber' : IDL.Nat,
  });
  const AddTrainInput = IDL.Record({
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'trainNumber' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'classes' : IDL.Vec(TrainClass),
    'route' : IDL.Vec(RouteStop),
  });
  const TrainId = IDL.Nat;
  const TrainView = IDL.Record({
    'id' : TrainId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'trainNumber' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'classes' : IDL.Vec(TrainClass),
    'route' : IDL.Vec(RouteStop),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const BookingType = IDL.Variant({
    'Bus' : IDL.Null,
    'Flight' : IDL.Null,
    'Train' : IDL.Null,
    'Hotel' : IDL.Null,
  });
  const MealEligibilityResult = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'eligible' : IDL.Bool,
    'campaignName' : IDL.Opt(IDL.Text),
    'mealTypes' : IDL.Vec(IDL.Text),
  });
  const PassengerDetail = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'seatNumber' : IDL.Text,
  });
  const CreateBookingInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'passengerDetails' : IDL.Vec(PassengerDetail),
    'toLocation' : IDL.Text,
    'referenceId' : IDL.Nat,
    'fromLocation' : IDL.Text,
    'distanceKm' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'bookingType' : BookingType,
    'travelDate' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Refunded' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const MealType = IDL.Variant({
    'Veg' : IDL.Null,
    'NonVeg' : IDL.Null,
    'Beverages' : IDL.Null,
    'Snacks' : IDL.Null,
  });
  const SpecialFeatures = IDL.Record({
    'freeFoodCouponCode' : IDL.Opt(IDL.Text),
    'freeFoodIncluded' : IDL.Bool,
    'mealType' : IDL.Opt(MealType),
  });
  const BookingView = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'passengerDetails' : IDL.Vec(PassengerDetail),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'toLocation' : IDL.Text,
    'referenceId' : IDL.Nat,
    'fromLocation' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'bookingType' : BookingType,
    'travelDate' : IDL.Text,
    'specialFeatures' : SpecialFeatures,
  });
  const UpdateUserInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'VIP' : IDL.Null,
    'User' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserView = IDL.Record({
    'id' : UserId,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'totalBookings' : IDL.Nat,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'isFirstTimeUser' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingBookings' : IDL.Nat,
    'activeBuses' : IDL.Nat,
    'activeHotels' : IDL.Nat,
    'activeFlights' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'activeTrains' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCoupons' : IDL.Nat,
    'activeMealCampaigns' : IDL.Nat,
  });
  const LoyaltyTxId = IDL.Nat;
  const LoyaltyTransactionType = IDL.Variant({
    'Earn' : IDL.Null,
    'Redeem' : IDL.Null,
  });
  const LoyaltyTransaction = IDL.Record({
    'id' : LoyaltyTxId,
    'bookingId' : IDL.Opt(BookingId),
    'transactionType' : LoyaltyTransactionType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'points' : IDL.Nat,
  });
  const PaymentId = IDL.Nat;
  const PaymentTransactionStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Success' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'NetBanking' : IDL.Null,
    'Wallet' : IDL.Null,
  });
  const PaymentView = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentTransactionStatus,
    'method' : PaymentMethod,
    'bookingId' : BookingId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const RevenuePeriod = IDL.Variant({
    'Day' : IDL.Null,
    'Week' : IDL.Null,
    'Year' : IDL.Null,
    'Month' : IDL.Null,
  });
  const RevenueStats = IDL.Record({
    'period' : RevenuePeriod,
    'bookingsByType' : IDL.Vec(
      IDL.Record({
        'revenue' : IDL.Nat,
        'count' : IDL.Nat,
        'bookingType' : IDL.Text,
      })
    ),
    'totalRevenue' : IDL.Nat,
  });
  const RoomId = IDL.Nat;
  const RoomType = IDL.Variant({
    'Suite' : IDL.Null,
    'Double' : IDL.Null,
    'Deluxe' : IDL.Null,
    'Single' : IDL.Null,
  });
  const RoomView = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'hotelId' : HotelId,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'available' : IDL.Bool,
    'capacity' : IDL.Nat,
    'price' : IDL.Nat,
    'roomType' : RoomType,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'System' : IDL.Null,
    'Booking' : IDL.Null,
    'Offer' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const ProcessPaymentInput = IDL.Record({
    'method' : PaymentMethod,
    'bookingId' : BookingId,
    'amount' : IDL.Nat,
  });
  const UpdateBusInput = IDL.Record({
    'id' : BusId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'droppingPoints' : IDL.Vec(IDL.Text),
    'busType' : BusType,
    'boardingPoints' : IDL.Vec(IDL.Text),
    'arrivalTime' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'operatorName' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'totalSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
  });
  const UpdateCouponInput = IDL.Record({
    'id' : CouponId,
    'discountValue' : IDL.Nat,
    'expiresAt' : Timestamp,
    'maxDiscount' : IDL.Nat,
    'minBookingAmount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Nat,
    'applicableFor' : CouponApplicableFor,
  });
  const UpdateFlightInput = IDL.Record({
    'id' : FlightId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'flightNumber' : IDL.Text,
    'departureTime' : IDL.Text,
    'cabin' : CabinClass,
    'from' : IDL.Text,
    'baggage' : IDL.Text,
    'stops' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'airline' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UpdateHotelInput = IDL.Record({
    'id' : HotelId,
    'availableRooms' : IDL.Nat,
    'starRating' : IDL.Nat,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'checkInTime' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'checkOutTime' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'totalRooms' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UpdateMealCampaignInput = IDL.Record({
    'id' : MealCampaignId,
    'endDate' : Timestamp,
    'eligibleForFirstTime' : IDL.Bool,
    'name' : IDL.Text,
    'eligibleForVIP' : IDL.Bool,
    'isActive' : IDL.Bool,
    'minDistanceKm' : IDL.Nat,
    'startDate' : Timestamp,
    'mealTypes' : IDL.Vec(IDL.Text),
  });
  const UpdateTrainInput = IDL.Record({
    'id' : TrainId,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'trainNumber' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'classes' : IDL.Vec(TrainClass),
    'route' : IDL.Vec(RouteStop),
  });
  const ValidateCouponResult = IDL.Record({
    'valid' : IDL.Bool,
    'discountAmount' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBus' : IDL.Func([AddBusInput], [BusView], []),
    'addCoupon' : IDL.Func([AddCouponInput], [CouponView], []),
    'addFlight' : IDL.Func([AddFlightInput], [FlightView], []),
    'addHotel' : IDL.Func([AddHotelInput], [HotelView], []),
    'addMealCampaign' : IDL.Func(
        [AddMealCampaignInput],
        [MealCampaignView],
        [],
      ),
    'addReview' : IDL.Func([AddReviewInput], [ReviewView], []),
    'addTrain' : IDL.Func([AddTrainInput], [TrainView], []),
    'approveReview' : IDL.Func([ReviewId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'callOpenAI' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'checkMealEligibility' : IDL.Func(
        [IDL.Nat, BookingType],
        [MealEligibilityResult],
        ['query'],
      ),
    'createBooking' : IDL.Func([CreateBookingInput], [BookingView], []),
    'createOrUpdateUser' : IDL.Func([UpdateUserInput], [UserView], []),
    'deleteBus' : IDL.Func([BusId], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
    'deleteFlight' : IDL.Func([FlightId], [IDL.Bool], []),
    'deleteHotel' : IDL.Func([HotelId], [IDL.Bool], []),
    'deleteTrain' : IDL.Func([TrainId], [IDL.Bool], []),
    'getActiveMealCampaigns' : IDL.Func(
        [],
        [IDL.Vec(MealCampaignView)],
        ['query'],
      ),
    'getAdminDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(ReviewView)], ['query']),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
    'getBus' : IDL.Func([BusId], [IDL.Opt(BusView)], ['query']),
    'getBuses' : IDL.Func([], [IDL.Vec(BusView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(CouponView)], ['query']),
    'getFlight' : IDL.Func([FlightId], [IDL.Opt(FlightView)], ['query']),
    'getFlights' : IDL.Func([], [IDL.Vec(FlightView)], ['query']),
    'getHotel' : IDL.Func([HotelId], [IDL.Opt(HotelView)], ['query']),
    'getHotels' : IDL.Func([], [IDL.Vec(HotelView)], ['query']),
    'getLoyaltyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getLoyaltyHistory' : IDL.Func(
        [],
        [IDL.Vec(LoyaltyTransaction)],
        ['query'],
      ),
    'getMealCampaigns' : IDL.Func([], [IDL.Vec(MealCampaignView)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'getPaymentByBooking' : IDL.Func(
        [BookingId],
        [IDL.Opt(PaymentView)],
        ['query'],
      ),
    'getRevenueStats' : IDL.Func([RevenuePeriod], [RevenueStats], ['query']),
    'getReviews' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(ReviewView)],
        ['query'],
      ),
    'getRoomsByHotel' : IDL.Func([HotelId], [IDL.Vec(RoomView)], ['query']),
    'getTrain' : IDL.Func([TrainId], [IDL.Opt(TrainView)], ['query']),
    'getTrains' : IDL.Func([], [IDL.Vec(TrainView)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(PaymentView)], ['query']),
    'getUserNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'processPayment' : IDL.Func([ProcessPaymentInput], [PaymentView], []),
    'searchBuses' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(BusView)],
        ['query'],
      ),
    'searchFlights' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(FlightView)],
        ['query'],
      ),
    'searchHotels' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(HotelView)],
        ['query'],
      ),
    'searchTrains' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(TrainView)],
        ['query'],
      ),
    'sendNotificationToUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, NotificationType],
        [],
        [],
      ),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus],
        [IDL.Bool],
        [],
      ),
    'updateBus' : IDL.Func([UpdateBusInput], [IDL.Opt(BusView)], []),
    'updateCoupon' : IDL.Func([UpdateCouponInput], [IDL.Opt(CouponView)], []),
    'updateFlight' : IDL.Func([UpdateFlightInput], [IDL.Opt(FlightView)], []),
    'updateHotel' : IDL.Func([UpdateHotelInput], [IDL.Opt(HotelView)], []),
    'updateMealCampaign' : IDL.Func(
        [UpdateMealCampaignInput],
        [IDL.Opt(MealCampaignView)],
        [],
      ),
    'updateTrain' : IDL.Func([UpdateTrainInput], [IDL.Opt(TrainView)], []),
    'updateUserProfile' : IDL.Func([UpdateUserInput], [UserView], []),
    'validateCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat, BookingType],
        [ValidateCouponResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };