/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddBusInput {
  'to' : string,
  'duration' : string,
  'droppingPoints' : Array<string>,
  'busType' : BusType,
  'boardingPoints' : Array<string>,
  'arrivalTime' : string,
  'cancellationPolicy' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'operatorName' : string,
  'amenities' : Array<string>,
  'totalSeats' : bigint,
  'price' : bigint,
}
export interface AddCouponInput {
  'discountValue' : bigint,
  'expiresAt' : Timestamp,
  'maxDiscount' : bigint,
  'minBookingAmount' : bigint,
  'code' : string,
  'discountType' : DiscountType,
  'usageLimit' : bigint,
  'applicableFor' : CouponApplicableFor,
}
export interface AddFlightInput {
  'to' : string,
  'duration' : string,
  'arrivalTime' : string,
  'flightNumber' : string,
  'departureTime' : string,
  'cabin' : CabinClass,
  'from' : string,
  'baggage' : string,
  'stops' : bigint,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : bigint,
}
export interface AddHotelInput {
  'starRating' : bigint,
  'city' : string,
  'pricePerNight' : bigint,
  'name' : string,
  'checkInTime' : string,
  'amenities' : Array<string>,
  'address' : string,
  'checkOutTime' : string,
  'totalRooms' : bigint,
  'images' : Array<string>,
}
export interface AddMealCampaignInput {
  'endDate' : Timestamp,
  'eligibleForFirstTime' : boolean,
  'name' : string,
  'eligibleForVIP' : boolean,
  'minDistanceKm' : bigint,
  'startDate' : Timestamp,
  'mealTypes' : Array<string>,
}
export interface AddReviewInput {
  'referenceId' : bigint,
  'comment' : string,
  'bookingType' : string,
  'rating' : bigint,
}
export interface AddTrainInput {
  'to' : string,
  'duration' : string,
  'trainNumber' : string,
  'arrivalTime' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'classes' : Array<TrainClass>,
  'route' : Array<RouteStop>,
}
export type BookingId = bigint;
export type BookingStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type BookingType = { 'Bus' : null } |
  { 'Flight' : null } |
  { 'Train' : null } |
  { 'Hotel' : null };
export interface BookingView {
  'id' : BookingId,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'passengerDetails' : Array<PassengerDetail>,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'toLocation' : string,
  'referenceId' : bigint,
  'fromLocation' : string,
  'totalAmount' : bigint,
  'bookingType' : BookingType,
  'travelDate' : string,
  'specialFeatures' : SpecialFeatures,
}
export type BusId = bigint;
export type BusType = { 'NonAC_Seater' : null } |
  { 'AC_Sleeper' : null } |
  { 'NonAC_Sleeper' : null } |
  { 'AC_Seater' : null };
export interface BusView {
  'id' : BusId,
  'to' : string,
  'duration' : string,
  'droppingPoints' : Array<string>,
  'busType' : BusType,
  'boardingPoints' : Array<string>,
  'arrivalTime' : string,
  'cancellationPolicy' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'operatorName' : string,
  'amenities' : Array<string>,
  'totalSeats' : bigint,
  'availableSeats' : bigint,
  'rating' : number,
  'price' : bigint,
}
export type CabinClass = { 'Business' : null } |
  { 'First' : null } |
  { 'Economy' : null };
export type CouponApplicableFor = { 'All' : null } |
  { 'Bus' : null } |
  { 'Flight' : null } |
  { 'Train' : null } |
  { 'Hotel' : null };
export type CouponId = bigint;
export interface CouponView {
  'id' : CouponId,
  'discountValue' : bigint,
  'expiresAt' : Timestamp,
  'maxDiscount' : bigint,
  'minBookingAmount' : bigint,
  'code' : string,
  'discountType' : DiscountType,
  'usedCount' : bigint,
  'isActive' : boolean,
  'usageLimit' : bigint,
  'applicableFor' : CouponApplicableFor,
}
export interface CreateBookingInput {
  'couponCode' : [] | [string],
  'passengerDetails' : Array<PassengerDetail>,
  'toLocation' : string,
  'referenceId' : bigint,
  'fromLocation' : string,
  'distanceKm' : bigint,
  'totalAmount' : bigint,
  'bookingType' : BookingType,
  'travelDate' : string,
}
export interface DashboardStats {
  'pendingBookings' : bigint,
  'activeBuses' : bigint,
  'activeHotels' : bigint,
  'activeFlights' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'activeTrains' : bigint,
  'confirmedBookings' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'totalCoupons' : bigint,
  'activeMealCampaigns' : bigint,
}
export type DiscountType = { 'Percent' : null } |
  { 'Fixed' : null };
export type FlightId = bigint;
export interface FlightView {
  'id' : FlightId,
  'to' : string,
  'duration' : string,
  'arrivalTime' : string,
  'flightNumber' : string,
  'departureTime' : string,
  'cabin' : CabinClass,
  'from' : string,
  'baggage' : string,
  'createdAt' : Timestamp,
  'stops' : bigint,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : bigint,
}
export type HotelId = bigint;
export interface HotelView {
  'id' : HotelId,
  'availableRooms' : bigint,
  'starRating' : bigint,
  'city' : string,
  'pricePerNight' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'checkInTime' : string,
  'amenities' : Array<string>,
  'address' : string,
  'rating' : number,
  'checkOutTime' : string,
  'reviewCount' : bigint,
  'totalRooms' : bigint,
  'images' : Array<string>,
}
export interface LoyaltyTransaction {
  'id' : LoyaltyTxId,
  'bookingId' : [] | [BookingId],
  'transactionType' : LoyaltyTransactionType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'points' : bigint,
}
export type LoyaltyTransactionType = { 'Earn' : null } |
  { 'Redeem' : null };
export type LoyaltyTxId = bigint;
export type MealCampaignId = bigint;
export interface MealCampaignView {
  'id' : MealCampaignId,
  'endDate' : Timestamp,
  'eligibleForFirstTime' : boolean,
  'name' : string,
  'eligibleForVIP' : boolean,
  'isActive' : boolean,
  'minDistanceKm' : bigint,
  'startDate' : Timestamp,
  'mealTypes' : Array<string>,
}
export interface MealEligibilityResult {
  'couponCode' : [] | [string],
  'eligible' : boolean,
  'campaignName' : [] | [string],
  'mealTypes' : Array<string>,
}
export type MealType = { 'Veg' : null } |
  { 'NonVeg' : null } |
  { 'Beverages' : null } |
  { 'Snacks' : null };
export type NotificationId = bigint;
export type NotificationType = { 'System' : null } |
  { 'Booking' : null } |
  { 'Offer' : null };
export interface NotificationView {
  'id' : NotificationId,
  'title' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export interface PassengerDetail {
  'age' : bigint,
  'name' : string,
  'seatNumber' : string,
}
export type PaymentId = bigint;
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'NetBanking' : null } |
  { 'Wallet' : null };
export type PaymentStatus = { 'Refunded' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export type PaymentTransactionStatus = { 'Failed' : null } |
  { 'Success' : null } |
  { 'Pending' : null };
export interface PaymentView {
  'id' : PaymentId,
  'status' : PaymentTransactionStatus,
  'method' : PaymentMethod,
  'bookingId' : BookingId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : bigint,
  'transactionId' : string,
}
export interface ProcessPaymentInput {
  'method' : PaymentMethod,
  'bookingId' : BookingId,
  'amount' : bigint,
}
export type RevenuePeriod = { 'Day' : null } |
  { 'Week' : null } |
  { 'Year' : null } |
  { 'Month' : null };
export interface RevenueStats {
  'period' : RevenuePeriod,
  'bookingsByType' : Array<
    { 'revenue' : bigint, 'count' : bigint, 'bookingType' : string }
  >,
  'totalRevenue' : bigint,
}
export type ReviewId = bigint;
export interface ReviewView {
  'id' : ReviewId,
  'userName' : string,
  'isApproved' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'referenceId' : bigint,
  'comment' : string,
  'bookingType' : string,
  'rating' : bigint,
}
export type RoomId = bigint;
export type RoomType = { 'Suite' : null } |
  { 'Double' : null } |
  { 'Deluxe' : null } |
  { 'Single' : null };
export interface RoomView {
  'id' : RoomId,
  'name' : string,
  'hotelId' : HotelId,
  'description' : string,
  'amenities' : Array<string>,
  'available' : boolean,
  'capacity' : bigint,
  'price' : bigint,
  'roomType' : RoomType,
}
export interface RouteStop {
  'arrivalTime' : string,
  'station' : string,
  'departureTime' : string,
  'dayNumber' : bigint,
}
export interface SpecialFeatures {
  'freeFoodCouponCode' : [] | [string],
  'freeFoodIncluded' : boolean,
  'mealType' : [] | [MealType],
}
export type Timestamp = bigint;
export interface TrainClass {
  'fare' : bigint,
  'available' : bigint,
  'className' : string,
}
export type TrainId = bigint;
export interface TrainView {
  'id' : TrainId,
  'to' : string,
  'duration' : string,
  'trainNumber' : string,
  'arrivalTime' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'classes' : Array<TrainClass>,
  'route' : Array<RouteStop>,
}
export interface UpdateBusInput {
  'id' : BusId,
  'to' : string,
  'duration' : string,
  'droppingPoints' : Array<string>,
  'busType' : BusType,
  'boardingPoints' : Array<string>,
  'arrivalTime' : string,
  'cancellationPolicy' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'operatorName' : string,
  'amenities' : Array<string>,
  'totalSeats' : bigint,
  'availableSeats' : bigint,
  'rating' : number,
  'price' : bigint,
}
export interface UpdateCouponInput {
  'id' : CouponId,
  'discountValue' : bigint,
  'expiresAt' : Timestamp,
  'maxDiscount' : bigint,
  'minBookingAmount' : bigint,
  'isActive' : boolean,
  'usageLimit' : bigint,
  'applicableFor' : CouponApplicableFor,
}
export interface UpdateFlightInput {
  'id' : FlightId,
  'to' : string,
  'duration' : string,
  'arrivalTime' : string,
  'flightNumber' : string,
  'departureTime' : string,
  'cabin' : CabinClass,
  'from' : string,
  'baggage' : string,
  'stops' : bigint,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : bigint,
}
export interface UpdateHotelInput {
  'id' : HotelId,
  'availableRooms' : bigint,
  'starRating' : bigint,
  'city' : string,
  'pricePerNight' : bigint,
  'name' : string,
  'checkInTime' : string,
  'amenities' : Array<string>,
  'address' : string,
  'rating' : number,
  'checkOutTime' : string,
  'reviewCount' : bigint,
  'totalRooms' : bigint,
  'images' : Array<string>,
}
export interface UpdateMealCampaignInput {
  'id' : MealCampaignId,
  'endDate' : Timestamp,
  'eligibleForFirstTime' : boolean,
  'name' : string,
  'eligibleForVIP' : boolean,
  'isActive' : boolean,
  'minDistanceKm' : bigint,
  'startDate' : Timestamp,
  'mealTypes' : Array<string>,
}
export interface UpdateTrainInput {
  'id' : TrainId,
  'to' : string,
  'duration' : string,
  'trainNumber' : string,
  'arrivalTime' : string,
  'departureTime' : string,
  'from' : string,
  'name' : string,
  'classes' : Array<TrainClass>,
  'route' : Array<RouteStop>,
}
export interface UpdateUserInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserId = Principal;
export type UserRole = { 'VIP' : null } |
  { 'User' : null } |
  { 'Admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserView {
  'id' : UserId,
  'referralCode' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'totalBookings' : bigint,
  'email' : string,
  'loyaltyPoints' : bigint,
  'isFirstTimeUser' : boolean,
  'phone' : string,
}
export interface ValidateCouponResult {
  'valid' : boolean,
  'discountAmount' : bigint,
  'message' : string,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBus' : ActorMethod<[AddBusInput], BusView>,
  'addCoupon' : ActorMethod<[AddCouponInput], CouponView>,
  'addFlight' : ActorMethod<[AddFlightInput], FlightView>,
  'addHotel' : ActorMethod<[AddHotelInput], HotelView>,
  'addMealCampaign' : ActorMethod<[AddMealCampaignInput], MealCampaignView>,
  'addReview' : ActorMethod<[AddReviewInput], ReviewView>,
  'addTrain' : ActorMethod<[AddTrainInput], TrainView>,
  'approveReview' : ActorMethod<[ReviewId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'callOpenAI' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'cancelBooking' : ActorMethod<[BookingId], boolean>,
  'checkMealEligibility' : ActorMethod<
    [bigint, BookingType],
    MealEligibilityResult
  >,
  'createBooking' : ActorMethod<[CreateBookingInput], BookingView>,
  'createOrUpdateUser' : ActorMethod<[UpdateUserInput], UserView>,
  'deleteBus' : ActorMethod<[BusId], boolean>,
  'deleteCoupon' : ActorMethod<[CouponId], boolean>,
  'deleteFlight' : ActorMethod<[FlightId], boolean>,
  'deleteHotel' : ActorMethod<[HotelId], boolean>,
  'deleteTrain' : ActorMethod<[TrainId], boolean>,
  'getActiveMealCampaigns' : ActorMethod<[], Array<MealCampaignView>>,
  'getAdminDashboardStats' : ActorMethod<[], DashboardStats>,
  'getAllBookings' : ActorMethod<[], Array<BookingView>>,
  'getAllReviews' : ActorMethod<[], Array<ReviewView>>,
  'getBooking' : ActorMethod<[BookingId], [] | [BookingView]>,
  'getBus' : ActorMethod<[BusId], [] | [BusView]>,
  'getBuses' : ActorMethod<[], Array<BusView>>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCoupons' : ActorMethod<[], Array<CouponView>>,
  'getFlight' : ActorMethod<[FlightId], [] | [FlightView]>,
  'getFlights' : ActorMethod<[], Array<FlightView>>,
  'getHotel' : ActorMethod<[HotelId], [] | [HotelView]>,
  'getHotels' : ActorMethod<[], Array<HotelView>>,
  'getLoyaltyBalance' : ActorMethod<[], bigint>,
  'getLoyaltyHistory' : ActorMethod<[], Array<LoyaltyTransaction>>,
  'getMealCampaigns' : ActorMethod<[], Array<MealCampaignView>>,
  'getMyBookings' : ActorMethod<[], Array<BookingView>>,
  'getPaymentByBooking' : ActorMethod<[BookingId], [] | [PaymentView]>,
  'getRevenueStats' : ActorMethod<[RevenuePeriod], RevenueStats>,
  'getReviews' : ActorMethod<[bigint, string], Array<ReviewView>>,
  'getRoomsByHotel' : ActorMethod<[HotelId], Array<RoomView>>,
  'getTrain' : ActorMethod<[TrainId], [] | [TrainView]>,
  'getTrains' : ActorMethod<[], Array<TrainView>>,
  'getTransactionHistory' : ActorMethod<[], Array<PaymentView>>,
  'getUserNotifications' : ActorMethod<[], Array<NotificationView>>,
  'getUserProfile' : ActorMethod<[], [] | [UserView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'processPayment' : ActorMethod<[ProcessPaymentInput], PaymentView>,
  'searchBuses' : ActorMethod<[string, string, string], Array<BusView>>,
  'searchFlights' : ActorMethod<
    [string, string, string, string, string],
    Array<FlightView>
  >,
  'searchHotels' : ActorMethod<
    [string, string, string, bigint, bigint],
    Array<HotelView>
  >,
  'searchTrains' : ActorMethod<
    [string, string, string, string],
    Array<TrainView>
  >,
  'sendNotificationToUser' : ActorMethod<
    [Principal, string, string, NotificationType],
    undefined
  >,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], boolean>,
  'updateBus' : ActorMethod<[UpdateBusInput], [] | [BusView]>,
  'updateCoupon' : ActorMethod<[UpdateCouponInput], [] | [CouponView]>,
  'updateFlight' : ActorMethod<[UpdateFlightInput], [] | [FlightView]>,
  'updateHotel' : ActorMethod<[UpdateHotelInput], [] | [HotelView]>,
  'updateMealCampaign' : ActorMethod<
    [UpdateMealCampaignInput],
    [] | [MealCampaignView]
  >,
  'updateTrain' : ActorMethod<[UpdateTrainInput], [] | [TrainView]>,
  'updateUserProfile' : ActorMethod<[UpdateUserInput], UserView>,
  'validateCoupon' : ActorMethod<
    [string, bigint, BookingType],
    ValidateCouponResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];